# Generated by Django 4.2.29 on 2026-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
