# Generated by Django 6.0.1 on 2026-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embeddings_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
